---
- name: Create instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    service_account_email: ""
    credentials_file: ""
    project_id: project-1-196510
    machine_type: n1-standard-2
    image: ubuntu-1604-xenial-v20180222
    zone: us-east1-b
  tasks:

   - name: Launch instances
     gce:
         instance_names: dev
         zone: "{{ zone }}"
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
